"use client";
import {useEffect,useState} from "react";import ReadingTable from "@/components/ReadingTable";import ImpactChart from "@/components/ImpactChart";
type Data={fields:any[];readings:any[];daily:any[];totals:any;weather:any;alerts:any[]};type Sim={fields:any[];total:any};
export default function Home(){const[data,setData]=useState<Data|null>(null),[sim,setSim]=useState<Sim|null>(null);useEffect(()=>{Promise.all([fetch("/api/dashboard",{cache:"no-store"}).then(r=>r.json()),fetch("/api/simulator",{cache:"no-store"}).then(r=>r.json())]).then(([d,s])=>{setData(d);setSim(s)})},[]);if(!data)return <main className="min-h-screen p-8 text-emerald-100">Loading FarmMind…</main>;const w=data.weather;const saved=sim?.total?.water_saved_l||0;return <main className="min-h-screen px-5 py-7 lg:px-10"><div className="mx-auto max-w-[1500px]">
<header className="mb-8 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 text-sm font-semibold tracking-[0.25em] text-emerald-400">FARMMIND</div><h1 className="text-4xl font-bold tracking-tight lg:text-5xl">Farm intelligence that explains every drop.</h1><p className="mt-3 max-w-3xl text-slate-400">A deterministic farm decision system using real weather, soil conditions, crop stage and water availability — no AI required.</p></div><div className="rounded-full border border-emerald-900 bg-emerald-950/40 px-4 py-2 text-sm text-emerald-300">● Live weather · PostgreSQL · Redis</div></header>
<section className="grid gap-4 md:grid-cols-5">{[["Fields",data.fields.length],["Readings",Number(data.totals.readings).toLocaleString()],["Water used",`${Number(data.totals.water_used_l).toLocaleString()} L`],["Irrigation events",data.totals.irrigation_events],["30-day projected saving",`${Number(saved).toLocaleString()} L`]].map(([k,v])=><div key={String(k)} className="glass rounded-2xl p-5"><div className="text-sm text-slate-400">{k}</div><div className="mt-2 text-2xl font-bold">{v}</div></div>)}</section>
<section className="mt-5 glass rounded-2xl p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-semibold">Live weather · Chittoor</h2><p className="text-sm text-slate-400">Open-Meteo forecast is used directly by the irrigation rules.</p></div><div className="text-sm text-emerald-300">Next 6h: {w?.next_6h?.rain_probability_pct}% rain risk · {w?.next_6h?.expected_rain_mm} mm expected</div></div><div className="mt-4 grid gap-3 sm:grid-cols-4"><Metric t="Temperature" v={w?.current?.temperature_c+"°C"}/><Metric t="Humidity" v={w?.current?.humidity_pct+"%"}/><Metric t="Rain now" v={w?.current?.rain_mm+" mm"}/><Metric t="Wind" v={w?.current?.wind_kmh+" km/h"}/></div><div className="mt-5 grid gap-2 md:grid-cols-7">{w?.daily?.map((d:any)=><div key={d.date} className="rounded-xl border border-emerald-950 bg-[#0a1810] p-3 text-center"><div className="text-xs text-slate-500">{d.date.slice(5)}</div><div className="mt-2 font-semibold">{d.temperature_max_c}°</div><div className="text-xs text-sky-300">{d.rain_probability_pct}% · {d.expected_rain_mm}mm</div></div>)}</div></section>
{data.alerts.length>0&&<section className="mt-5 glass rounded-2xl p-5"><h2 className="text-lg font-semibold">Farm alerts</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{data.alerts.map((a:any,i:number)=><div key={i} className="rounded-xl border border-emerald-950 bg-[#0a1810] p-4"><span className="mr-2 text-xs uppercase text-amber-300">{a.severity}</span>{a.message}</div>)}</div></section>}
<section className="mt-5 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="glass rounded-2xl p-5"><h2 className="text-lg font-semibold">30-day water simulator</h2><p className="mb-4 text-sm text-slate-400">Rule-based estimate comparing traditional watering with FarmMind weather-aware scheduling.</p>{sim&&<div className="grid gap-3 sm:grid-cols-3 mb-5"><Metric t="Traditional" v={Number(sim.total.traditional_water_l).toLocaleString()+" L"}/><Metric t="FarmMind" v={Number(sim.total.farmmind_water_l).toLocaleString()+" L"}/><Metric t="Projected saving" v={Number(saved).toLocaleString()+" L"}/></div>}<div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b border-emerald-950 text-left text-slate-500"><th className="p-3">Field</th><th className="p-3">Traditional</th><th className="p-3">FarmMind</th><th className="p-3">Saved</th></tr></thead><tbody>{sim?.fields.map((f:any)=><tr key={f.field_id} className="border-b border-emerald-950/60"><td className="p-3">{f.name}</td><td className="p-3">{f.traditional_water_l.toLocaleString()} L</td><td className="p-3">{f.farmmind_water_l.toLocaleString()} L</td><td className="p-3 text-emerald-300">{f.water_saved_pct}%</td></tr>)}</tbody></table></div></div>
<div className="glass rounded-2xl p-5"><h2 className="text-lg font-semibold">Field map & priority</h2><div className="mt-4 grid grid-cols-2 gap-2">{data.fields.map((f:any)=><div key={f.id} className={`min-h-28 rounded-xl border p-4 ${f.moisture_status==="CRITICAL"?"border-red-900 bg-red-950/30":f.recommendation?.action==="IRRIGATE"?"border-amber-800 bg-amber-950/20":"border-emerald-900 bg-emerald-950/20"}`}><div className="text-xs text-slate-500">{f.id}</div><b>{f.name}</b><div className="mt-2 text-sm">{f.soil_moisture}% moisture</div><div className="mt-1 text-xs text-emerald-300">{f.recommendation?.action} · {f.recommendation?.water_l||0} L</div></div>)}</div><div className="mt-4 text-sm text-slate-400">Priority uses moisture deficit, crop stage, soil type, rain forecast and available water.</div></div></section>
<section className="mt-5 glass rounded-2xl p-5"><h2 className="text-lg font-semibold">Water & decision trend</h2><p className="text-sm text-slate-400">Last 14 days from PostgreSQL.</p><ImpactChart data={data.daily}/></section>
<section className="mt-5 glass rounded-2xl p-5"><div className="mb-4"><h2 className="text-lg font-semibold">Farm sensor history</h2><p className="text-sm text-slate-400">1,000 latest records with virtualized rendering.</p></div><ReadingTable data={data.readings}/></section>
<footer className="py-8 text-center text-xs text-slate-500">FarmMind · Next.js · Tailwind · PostgreSQL · Redis · Open-Meteo · deterministic irrigation engine</footer></div></main>}
function Metric({t,v}:{t:string;v:any}){return <div className="rounded-xl border border-emerald-950 bg-[#0a1810] p-4"><div className="text-xs text-slate-500">{t}</div><div className="mt-1 text-2xl font-bold">{v}</div></div>}