"use client";
import {useEffect,useState} from "react";import ReadingTable from "@/components/ReadingTable";import ImpactChart from "@/components/ImpactChart";
type Data={fields:any[];readings:any[];daily:any[];totals:any;weather:any;alerts:any[];water:any;irrigation_events:any[]};type Sim={fields:any[];total:any};
export default function Home(){const[data,setData]=useState<Data|null>(null),[sim,setSim]=useState<Sim|null>(null),[refill,setRefill]=useState("1000"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
const load=()=>Promise.all([fetch("/api/dashboard",{cache:"no-store"}).then(r=>r.json()),fetch("/api/simulator",{cache:"no-store"}).then(r=>r.json())]).then(([d,s])=>{setData(d);setSim(s)});useEffect(()=>{load()},[]);if(!data)return <main className="min-h-screen p-8 text-emerald-100">Loading FarmMind...</main>;
const w=data.weather,saved=sim?.total?.water_saved_l||0;
async function refillWater(){setBusy(true);const r=await fetch("/api/water",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount_l:Number(refill)})});const j=await r.json();setMessage(r.ok?"Water balance updated: "+Math.round(j.current_l)+" L available.":j.error);await load();setBusy(false)}
async function execute(f:any){const water=Number(f.recommendation?.water_l||0);if(water<=0){setMessage("This field is currently recommended to WAIT.");return}const after=Math.min(Number(f.target_moisture),Number(f.soil_moisture)+Math.max(5,water/(Number(f.area_m2)*.7)));setBusy(true);const r=await fetch("/api/irrigation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({field_id:f.id,water_l:water,moisture_after:Number(after.toFixed(1)),pump_flow_lpm:Number(f.pump_flow_l)||20,notes:"Executed from FarmMind dashboard"})});const j=await r.json();setMessage(r.ok?"Irrigation recorded for "+f.name+": "+Math.round(water)+" L, "+Number(j.event.pump_minutes).toFixed(1)+" min.":j.error);await load();setBusy(false)}
return <main className="min-h-screen px-5 py-7 lg:px-10"><div className="mx-auto max-w-[1500px]">
<header className="mb-8 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 text-sm font-semibold tracking-[0.25em] text-emerald-400">FARMMIND</div><h1 className="text-4xl font-bold tracking-tight lg:text-5xl">Farm intelligence that explains every drop.</h1><p className="mt-3 max-w-3xl text-slate-400">A deterministic farm decision system using real weather, soil conditions, crop stage and water availability — no AI required.</p></div><div className="rounded-full border border-emerald-900 bg-emerald-950/40 px-4 py-2 text-sm text-emerald-300">Live · PostgreSQL · Redis</div></header>
<section className="grid gap-4 md:grid-cols-5">{[["Fields",data.fields.length],["Readings",Number(data.totals.readings).toLocaleString()],["Water used",Number(data.totals.water_used_l).toLocaleString()+" L"],["Irrigation events",data.totals.irrigation_events],["30-day projected saving",Number(saved).toLocaleString()+" L"]].map(([k,v])=><div key={String(k)} className="glass rounded-2xl p-5"><div className="text-sm text-slate-400">{k}</div><div className="mt-2 text-2xl font-bold">{v}</div></div>)}</section>
<section className="mt-5 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="glass rounded-2xl p-5"><h2 className="text-lg font-semibold">Live farm water balance</h2><p className="mt-1 text-sm text-slate-400">{data.water?.source} · dynamic after every irrigation</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric t="Available" v={Math.round(data.water?.current_l||0)+" L"}/><Metric t="Capacity" v={Math.round(data.water?.capacity_l||0)+" L"}/><Metric t="Refilled" v={Math.round(data.water?.refill_l||0)+" L"}/></div><div className="mt-4 flex gap-2"><input value={refill} onChange={e=>setRefill(e.target.value)} className="w-32 rounded-xl border border-emerald-900 bg-[#0a1810] p-3" type="number"/><button disabled={busy} onClick={refillWater} className="rounded-xl bg-emerald-700 px-4 py-2 font-semibold">Refill water</button></div></div><div className="glass rounded-2xl p-5"><h2 className="text-lg font-semibold">Execution status</h2><p className="mt-2 text-sm text-slate-400">{message||"Recommendations can now be executed and recorded."}</p><div className="mt-4 text-sm"><b>Latest:</b> {data.irrigation_events?.[0]?data.irrigation_events[0].name+" · "+Math.round(data.irrigation_events[0].water_l)+" L · "+Number(data.irrigation_events[0].pump_minutes).toFixed(1)+" min":"No execution yet"}</div></div></section>
<section className="mt-5 glass rounded-2xl p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-semibold">Live weather · Chittoor</h2><p className="text-sm text-slate-400">Open-Meteo forecast feeds the deterministic irrigation rules.</p></div><div className="text-sm text-emerald-300">Next 6h: {w?.next_6h?.rain_probability_pct}% rain risk · {w?.next_6h?.expected_rain_mm} mm</div></div><div className="mt-4 grid gap-3 sm:grid-cols-4"><Metric t="Temperature" v={w?.current?.temperature_c+"°C"}/><Metric t="Humidity" v={w?.current?.humidity_pct+"%"}/><Metric t="Rain now" v={w?.current?.rain_mm+" mm"}/><Metric t="Wind" v={w?.current?.wind_kmh+" km/h"}/></div></section>
{data.alerts.length>0&&<section className="mt-5 glass rounded-2xl p-5"><h2 className="text-lg font-semibold">Farm alerts</h2><div className="mt-3 grid gap-2 md:grid-cols-2">{data.alerts.map((a:any,i:number)=><div key={i} className="rounded-xl border border-emerald-950 bg-[#0a1810] p-4"><span className="mr-2 text-xs uppercase text-amber-300">{a.severity}</span>{a.message}</div>)}</div></section>}
<section className="mt-5 glass rounded-2xl p-5"><h2 className="text-lg font-semibold">Field control center</h2><p className="text-sm text-slate-400">Edit moisture, field water and pump flow. Execute recommendations and record before/after moisture.</p><div className="mt-4 grid gap-4 lg:grid-cols-3">{data.fields.map((f:any)=><FieldCard key={f.id} f={f} busy={busy} onExecute={()=>execute(f)} onSave={async(p:any)=>{setBusy(true);const r=await fetch("/api/fields",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(p)});const j=await r.json();setMessage(r.ok?f.name+" updated.":j.error);await load();setBusy(false)}}/>)}</div></section>
<section className="mt-5 glass rounded-2xl p-5"><h2 className="text-lg font-semibold">30-day water simulator</h2><p className="mb-4 text-sm text-slate-400">Rule-based estimate comparing traditional watering with FarmMind weather-aware scheduling.</p>{sim&&<div className="grid gap-3 sm:grid-cols-3 mb-5"><Metric t="Traditional" v={Number(sim.total.traditional_water_l).toLocaleString()+" L"}/><Metric t="FarmMind" v={Number(sim.total.farmmind_water_l).toLocaleString()+" L"}/><Metric t="Projected saving" v={Number(saved).toLocaleString()+" L"}/></div>}<div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b border-emerald-950 text-left text-slate-500"><th className="p-3">Field</th><th className="p-3">Traditional</th><th className="p-3">FarmMind</th><th className="p-3">Saved</th></tr></thead><tbody>{sim?.fields.map((f:any)=><tr key={f.field_id} className="border-b border-emerald-950/60"><td className="p-3">{f.name}</td><td className="p-3">{f.traditional_water_l.toLocaleString()} L</td><td className="p-3">{f.farmmind_water_l.toLocaleString()} L</td><td className="p-3 text-emerald-300">{f.water_saved_pct}%</td></tr>)}</tbody></table></div><div className="mt-3 text-xs text-amber-300">Estimated projection — not a measured agronomic guarantee.</div></section>
<section className="mt-5 glass rounded-2xl p-5"><h2 className="text-lg font-semibold">Water & decision trend</h2><ImpactChart data={data.daily}/></section><section className="mt-5 glass rounded-2xl p-5"><div className="mb-4"><h2 className="text-lg font-semibold">Farm sensor history</h2><p className="text-sm text-slate-400">1,000 latest records.</p></div><ReadingTable data={data.readings}/></section>
<footer className="py-8 text-center text-xs text-slate-500">FarmMind · Next.js · PostgreSQL · Redis · Open-Meteo · deterministic irrigation engine</footer></div></main>}
function FieldCard({f,busy,onExecute,onSave}:{f:any;busy:boolean;onExecute:()=>void;onSave:(p:any)=>void}){const[moisture,setMoisture]=useState(String(f.soil_moisture)),[water,setWater]=useState(String(f.water_available_l)),[flow,setFlow]=useState(String(f.pump_flow_lpm||20));return <div className="rounded-2xl border border-emerald-950 bg-[#0a1810] p-4"><div className="flex justify-between"><div><div className="text-xs text-slate-500">{f.id}</div><b>{f.name}</b><div className="text-xs text-slate-400">{f.crop} · {f.growth_stage} · {f.soil_type} · {f.area_m2} m²</div></div><span className="text-sm text-emerald-300">{f.recommendation?.action}</span></div><div className="mt-3 grid grid-cols-3 gap-2"><Mini label="Moisture %" value={moisture} setValue={setMoisture}/><Mini label="Field water L" value={water} setValue={setWater}/><Mini label="Pump L/min" value={flow} setValue={setFlow}/></div><div className="mt-3 rounded-xl border border-emerald-950 p-3 text-sm"><b>Recommendation:</b> {f.recommendation?.water_l||0} L · {f.recommendation?.pump_minutes||0} min · {f.recommendation?.reason}</div><div className="mt-3 flex gap-2"><button disabled={busy} onClick={()=>onSave({id:f.id,soil_moisture:Number(moisture),water_available_l:Number(water),pump_flow_lpm:Number(flow)})} className="rounded-xl border border-emerald-800 px-3 py-2 text-sm">Save field</button><button disabled={busy||f.recommendation?.action!=="IRRIGATE"} onClick={onExecute} className="rounded-xl bg-emerald-700 px-3 py-2 text-sm font-semibold disabled:opacity-40">Execute irrigation</button></div></div>}
function Mini({label,value,setValue}:{label:string;value:string;setValue:(v:string)=>void}){return <label className="text-xs text-slate-500">{label}<input value={value} onChange={e=>setValue(e.target.value)} type="number" className="mt-1 w-full rounded-lg border border-emerald-950 bg-[#08120c] p-2 text-sm text-white"/></label>}
function Metric({t,v}:{t:string;v:any}){return <div className="rounded-xl border border-emerald-950 bg-[#0a1810] p-4"><div className="text-xs text-slate-500">{t}</div><div className="mt-1 text-2xl font-bold">{v}</div></div>}